### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/animal-rescue-website#1]
@charlie-quinn

https://docs.google.com/spreadsheets/d/1k43hsBsP2xbrXPaZcSijJNP7aaofwnczhAyLPmUM83Q/edit?usp=sharing

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by cmvolden** [comment]
Thank you!
