### ISSUE TITLE
Request for grade

### ISSUE THREAD

**Issue by cmvolden** [cmvolden/animal-rescue-website#2]
@charlie-quinn

For this project, I would obviously like to get an A+ for how good I FEEL about it. Reasonably, think I am sitting somewhere around an A, A-.
 
Some problems I faced that I could not figure out were how to reduce line length, and how to get the distribute-content to work properly (cards are different heights). Thankfully through testing I was able to resolve a lot of the issues on the checklist prior to submitting it — mostly within the accessibility section — such as removing the <I> tag, adding required fields to my form, and highlighting the current page.

While testing I encountered the following issues:
-The bottom image on index.html and adopt.html appears excessively large on full screen sizes.
-The font Forum looks strange in Firefox.
-In Safari desktop, I cannot tab to skip links or into browser. This may be simply user error as I am not used to Safari.

As far as I can tell, the website is fully responsive. It passed all the checks and tests, as well as Markbot. The only issue was under performance for “Compress Transfer” and “Cache Static Content”. Unfortunately I have no idea what that means and do not recall learning how to do this. 

I think the website looks really nice, and achieves the goals I set out for the target audience within my research phase. I’m really happy that I finally learned how to embed images and use grids/units properly, as this is something I have struggled with for a long time. In addition, I am happy to have learned so much about increasing website performance. My choice of a darker background and smaller sized images reduces the carbon footprint of the website.

From where I'm currently sitting with a few missed assignments, I think it was the more beneficial route to take to code this website. And to gain experience coding websites from scratch, and be graded on it while I can. I look forward to your feedback and thank you for all your help this semester!

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by cmvolden** [comment]
Thank you @charlie-quinn ! Have a wonderful holiday!
